-- FXLM Presets Module
-- Handles preset management, loading, and saving

local dt = require "darktable"
local presets = {}

-- Preset storage directory
presets.storage_dir = dt.configuration.config_dir .. "/fxlm_presets/"

-- Ensure storage directory exists
function presets.ensure_storage_dir()
    local dir = io.popen("mkdir -p " .. presets.storage_dir)
    if dir then
        dir:close()
    end
end

-- Load all presets from storage
function presets.load_all()
    presets.ensure_storage_dir()
    
    local loaded_presets = {}
    
    -- Scan directory for .fxlm files
    local p = io.popen("find " .. presets.storage_dir .. " -name '*.fxlm' -type f")
    if not p then
        return loaded_presets
    end
    
    for file in p:lines() do
        local preset = presets.load_from_file(file)
        if preset then
            table.insert(loaded_presets, preset)
        end
    end
    
    p:close()
    return loaded_presets
end

-- Load a single preset from file
function presets.load_from_file(filepath)
    local file = io.open(filepath, "r")
    if not file then
        return nil
    end
    
    local content = file:read("*all")
    file:close()
    
    -- Parse the FXLM file
    local chunk, err = loadstring(content)
    if not chunk then
        dt.print("Error loading preset: " .. err)
        return nil
    end
    
    local success, preset_data = pcall(chunk)
    if not success then
        dt.print("Error executing preset: " .. preset_data)
        return nil
    end
    
    return preset_data
end

-- Save a preset to file
function presets.save_to_file(preset_data, filepath)
    presets.ensure_storage_dir()
    
    local file = io.open(filepath, "w")
    if not file then
        return false, "Could not open file for writing"
    end
    
    -- Convert to FXLM format
    local content = presets.to_fxlm_format(preset_data)
    
    file:write(content)
    file:close()
    
    return true, "Preset saved successfully"
end

-- Convert preset data to FXLM file format
function presets.to_fxlm_format(preset_data)
    local lines = {}
    
    table.insert(lines, "-- FXLM Preset File")
    table.insert(lines, "-- Generated by FXLM Plugin")
    table.insert(lines, "-- Date: " .. os.date("%Y-%m-%d %H:%M:%S"))
    table.insert(lines, "")
    
    table.insert(lines, "return {")
    table.insert(lines, "    name = \"" .. (preset_data.name or "Unnamed") .. "\",")
    table.insert(lines, "    description = \"" .. (preset_data.description or "") .. "\",")
    table.insert(lines, "    version = \"" .. (preset_data.version or "1.0") .. "\",")
    table.insert(lines, "    author = \"" .. (preset_data.author or "FXLM") .. "\",")
    table.insert(lines, "    intensity = " .. (preset_data.intensity or 100) .. ",")
    table.insert(lines, "    parameters = {")
    
    -- Add parameters
    if preset_data.parameters then
        for module_name, params in pairs(preset_data.parameters) do
            table.insert(lines, "        " .. module_name .. " = {")
            for param_name, param_value in pairs(params) do
                if type(param_value) == "string" then
                    table.insert(lines, "            " .. param_name .. " = \"" .. param_value .. "\",")
                else
                    table.insert(lines, "            " .. param_name .. " = " .. tostring(param_value) .. ",")
                end
            end
            table.insert(lines, "        },")
        end
    end
    
    table.insert(lines, "    },")
    table.insert(lines, "}")
    
    return table.concat(lines, "\n")
end

-- Create a new preset from current settings
function presets.create_from_current(name, description)
    local image = dt.gui_actions.get_current_image()
    if not image then
        return nil, "No image selected"
    end
    
    -- Get current module settings
    local parameters = {}
    
    -- This would read current Darktable module settings
    -- For now, we'll create a basic structure
    parameters.filmic_rgb = {
        contrast = 1.0,
        saturation = 1.0,
        highlight_compression = 0.5,
        shadow_compression = 0.5
    }
    
    parameters.color_balance_rgb = {
        saturation = 1.0,
        warmth = 0.0,
        tint = 0.0
    }
    
    parameters.grain = {
        amount = 0.1,
        size = 0.5,
        roughness = 0.5
    }
    
    parameters.vignette = {
        amount = 0.1,
        radius = 0.5,
        strength = 0.5
    }
    
    local preset_data = {
        name = name,
        description = description or "",
        version = "1.0",
        author = "FXLM User",
        intensity = 100,
        parameters = parameters
    }
    
    return preset_data, nil
end

-- Delete a preset
function presets.delete(preset_name)
    local filepath = presets.storage_dir .. preset_name .. ".fxlm"
    
    local p = io.popen("rm -f " .. filepath)
    if p then
        p:close()
        return true, "Preset deleted"
    end
    
    return false, "Could not delete preset"
end

-- Export preset as JSON (for sharing)
function presets.export_as_json(preset_data)
    local json = require "json"
    
    if not json then
        -- Fallback to simple string format
        local lines = {}
        table.insert(lines, "{")
        table.insert(lines, "  \"name\": \"" .. preset_data.name .. "\",")
        table.insert(lines, "  \"description\": \"" .. preset_data.description .. "\",")
        table.insert(lines, "  \"parameters\": {")
        
        if preset_data.parameters then
            for module_name, params in pairs(preset_data.parameters) do
                table.insert(lines, "    \"" .. module_name .. "\": {")
                for param_name, param_value in pairs(params) do
                    if type(param_value) == "string" then
                        table.insert(lines, "      \"" .. param_name .. "\": \"" .. param_value .. "\",")
                    else
                        table.insert(lines, "      \"" .. param_name .. "\": " .. tostring(param_value) .. ",")
                    end
                end
                table.insert(lines, "    },")
            end
        end
        
        table.insert(lines, "  }")
        table.insert(lines, "}")
        
        return table.concat(lines, "\n")
    end
    
    -- Use JSON library if available
    return json.encode(preset_data)
end

-- Import preset from JSON
function presets.import_from_json(json_string)
    local json = require "json"
    
    if not json then
        return nil, "JSON library not available"
    end
    
    local success, preset_data = pcall(json.decode, json_string)
    if not success then
        return nil, "Invalid JSON format"
    end
    
    -- Validate the imported preset
    local valid, errors = presets.validate(preset_data)
    if not valid then
        return nil, "Invalid preset: " .. table.concat(errors, ", ")
    end
    
    return preset_data, nil
end

-- Validate preset structure
function presets.validate(preset_data)
    local errors = {}
    
    if not preset_data.name then
        table.insert(errors, "Missing name")
    end
    
    if not preset_data.parameters then
        table.insert(errors, "Missing parameters")
    end
    
    return #errors == 0, errors
end

-- Get preset by name
function presets.get_by_name(name)
    local all_presets = presets.load_all()
    
    for _, preset in ipairs(all_presets) do
        if preset.name == name then
            return preset
        end
    end
    
    return nil
end

-- List all preset names
function presets.list_names()
    local all_presets = presets.load_all()
    local names = {}
    
    for _, preset in ipairs(all_presets) do
        table.insert(names, preset.name)
    end
    
    return names
end

-- Initialize presets module
presets.ensure_storage_dir()

return presets